name: notify-monitoring-person
on:
  schedule:
    - cron: '0 8 * * MON'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://fm-slack-bot.vercel.app/runjob' 
